name: Your New Jekyll Site
pygments: true

source:      .
destination: ./_site
layouts:     ./_layouts

post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: ia

exclude:
- assets
- README.md
- Rakefile
